apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: akmebank-app-pipelinerun
spec:
  serviceAccountName: tekton-github-account
  pipelineRef:
    name: akmebank-app-pipeline
  params:
  - name: GIT_USER_NAME
    value: hirokuni-kitahara
  - name: GIT_USER_EMAIL
    value: hirokuni.kitahara1@ibm.com
  resources:
  - name: sourcerepo
    resourceSpec:
      type: git
      params:
      - name: revision
        value: master
      - name: url
        value: https://github.com/gajananan/akmebank-app.git
  - name: kustomize-config-repo
    resourceSpec:
      type: git
      params:
      - name: revision
        value: main
      - name: url
        value: https://github.com/hirokuni-kitahara/akmebank-config.git
  - name: ui-image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/hk-image-registry/akmebank-ui:4.2.1
  - name: manifest-image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/hk-image-registry/akmebank-app-manifest:4.2.1

