apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: akmebank-app-pipelinerun
spec:
  serviceAccountName: tekton-github-account
  pipelineRef:
    name: akmebank-app-pipeline
  params:
  - name: manifestImageName
    value: gcr.io/hk-image-registry/akmebank-app-manifest:4.1.1
  resources:
  - name: sourcerepo
    resourceSpec:
      type: git
      params:
      - name: revision
        value: master
      - name: url
        value: https://github.com/gajananan/akmebank-app.git
  - name: kustomize-config-repo
    resourceSpec:
      type: git
      params:
      - name: revision
        value: demo1
      - name: url
        value: https://github.com/hirokuni-kitahara/akmebank-config.git
  - name: ui-image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/hk-image-registry/akmebank-ui:4.1.1
  - name: command-image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/hk-image-registry/account-command-ms:4.1.1
  - name: query-image
    resourceSpec:
      type: image
      params:
      - name: url
        value: gcr.io/hk-image-registry/account-query-ms:4.1.1
  # - name: manifest-image
  #   resourceSpec:
  #     type: image
  #     params:
  #     - name: url
  #       value: gcr.io/hk-image-registry/akmebank-app-manifest:4.1.1

