apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: akmebank-app-pipeline
spec:
  params:
  - name: manifestImageName
    type: string
    description: The image name of manifest
  resources:
  - name: sourcerepo
    type: git
  - name: kustomize-config-repo
    type: git
  - name: ui-image
    type: image
  - name: command-image
    type: image
  - name: query-image
    type: image
  # - name: manifest-image
  #   type: image
  tasks:
  #----------------------------------------------
  #  Task 1: build ui image
  #----------------------------------------------
  - name: build-ui-image
    taskRef:
      name: build-ui-image
    params:
      - name: pathToDockerFile
        value: ./Dockerfile
      - name: pathToContext
        value: /workspace/sourcerepo/akmebank-ui/
    resources:
      inputs:
      - name: sourcerepo
        resource: sourcerepo
      outputs:
      - name: builtImage
        resource: ui-image
  #----------------------------------------------
  #  Task 2: build command image
  #----------------------------------------------
  - name: build-command-image
    taskRef:
      name: build-command-image
    params:
      - name: pathToDockerFile
        value: ./src/main/docker/Dockerfile.jvm
      - name: pathToContext
        value: /workspace/sourcerepo/account-command-ms/
    resources:
      inputs:
      - name: sourcerepo
        resource: sourcerepo
      outputs:
      - name: builtImage
        resource: command-image
  #----------------------------------------------
  #  Task 3: build query image
  #----------------------------------------------
  - name: build-query-image
    taskRef:
      name: build-query-image
    params:
      - name: pathToDockerFile
        value: ./src/main/docker/Dockerfile.jvm
      - name: pathToContext
        value: /workspace/sourcerepo/account-query-ms/
    resources:
      inputs:
      - name: sourcerepo
        resource: sourcerepo
      outputs:
      - name: builtImage
        resource: query-image
  #----------------------------------------------
  #  Task 4: build manifest image
  #----------------------------------------------
  - name: build-manifest-and-deploy-app
    taskRef:
      name: build-manifest-and-deploy-app
    runAfter:
    - build-ui-image
    - build-command-image
    - build-query-image
    params:
      - name: pathToKustomizeBase
        value: /workspace/kustomize-config-repo/roles/dev
      - name: builtImageName
        value: $(params.manifestImageName)
    resources:
      inputs:
      - name: kustomize-config-repo
        resource: kustomize-config-repo